MVC_SIS/MVC_SIS/Models/Data/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Exercises.Models.Data
{
    public class Student : IValidatableObject
    {
        public int StudentId { get; set; }
        //[Required(ErrorMessage = "You must enter a first name!")]
        public string FirstName { get; set; }
        //[Required(ErrorMessage = "You must enter a last name!")]
        public string LastName { get; set; }
        //[Required(ErrorMessage = "You must enter a GPA!")]
        public decimal GPA { get; set; }
        public List<Address> Address { get; set; }
        //[Required(ErrorMessage = "You must choose a major!")]
        public Major Major { get; set; }
        //[Required(ErrorMessage = "You must choose at least one course!")]
        public List<Course> Courses { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> errors = new List<ValidationResult>();

            if (string.IsNullOrEmpty(FirstName))
            {
                errors.Add(new ValidationResult("The First Name field is required.", new[] { "FirstName" }));
            }
            if (string.IsNullOrEmpty(LastName))
            {
                errors.Add(new ValidationResult("The Last Name field is required.", new[] { "LastName" }));
            }
            if (string.IsNullOrEmpty(GPA.ToString()) || GPA>5||GPA<0)
            {
                errors.Add(new ValidationResult("You must enter a GPA between 0 and 5.", new[] { "GPA" }));
            }
            if (string.IsNullOrEmpty(Major.ToString()))
            {
                errors.Add(new ValidationResult("The Major field is required.", new[] { "Major" }));
            }

            return errors;
        }
    }
}

MVC_SIS/MVC_SIS/Controllers/AdminController.cs
using Exercises.Models.Data;
using Exercises.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Exercises.Controllers
{
    public class AdminController : Controller
    {

        [HttpGet]
        public ActionResult Majors()
        {
            var model = MajorRepository.GetAll();
            return View(model.ToList());
        }

        [HttpGet]
        public ActionResult AddMajor()
        {
            return View(new Major());
        }

        [HttpPost]
        public ActionResult AddMajor(Major major)
        {
            if (ModelState.IsValid)
            {
                MajorRepository.Add(major.MajorName);
                return RedirectToAction("Majors");
            }
            else
            {
                return View("AddMajor",new Major());
            }
            
        }

        [HttpGet]
        public ActionResult EditMajor(int id)
        {
            var major = MajorRepository.Get(id);
            return View(major);
        }

        [HttpPost]
        public ActionResult EditMajor(Major major)
        {
            if (ModelState.IsValid)
            {
                MajorRepository.Edit(major);
                return RedirectToAction("Majors");
            }
            else
            {
                var major2 = MajorRepository.Get(major.MajorId);
                return View("EditMajor",major2);
            }
            
        }

        [HttpGet]
        public ActionResult DeleteMajor(int id)
        {
            var major = MajorRepository.Get(id);
            return View(major);
        }

        [HttpPost]
        public ActionResult DeleteMajor(Major major)
        {
            MajorRepository.Delete(major.MajorId);
            return RedirectToAction("Majors");
        }

        [HttpGet]
        public ActionResult States()
        {
            var model = StateRepository.GetAll();
            return View(model.ToList());
        }

        [HttpGet]
        public ActionResult AddState()
        {
            return View(new State());
        }

        [HttpPost]
        public ActionResult AddState(State state)
        {
            if (ModelState.IsValid)
            {
                state.StateAbbreviation = state.StateAbbreviation.ToUpper();
                state.StateName = state.StateName.Substring(0, 1).ToUpper() + state.StateName.Substring(1);
                StateRepository.Add(state);
                return RedirectToAction("States");
            }
            else
            {
                return View("AddState", new State());
            }
            
        }

        [HttpGet]
        public ActionResult EditState(string id)
        {
            var state = StateRepository.Get(id);
            return View(state);
        }

        [HttpPost]
        public ActionResult EditState(State state)
        {
            if (ModelState.IsValid)
            {
                state.StateAbbreviation = state.StateAbbreviation.ToUpper();
                StateRepository.Edit(state);
                return RedirectToAction("States");
            }
            else
            {
                var state2 = StateRepository.Get(state.StateAbbreviation);
                return View("EditState",state2);
            }
        }

        [HttpGet]
        public ActionResult DeleteState(string id)
        {
            var state = StateRepository.Get(id);
            return View(state);
        }

        [HttpPost]
        public ActionResult DeleteState(State state)
        {
            StateRepository.Delete(state.StateAbbreviation);
            return RedirectToAction("States");
        }

        [HttpGet]
        public ActionResult Courses()
        {
            var model = CourseRepository.GetAll();
            return View(model.ToList());
        }

        [HttpGet]
        public ActionResult AddCourse()
        {
            return View(new Course());
        }

        [HttpPost]
        public ActionResult AddCourse(Course course)
        {
            if (ModelState.IsValid)
            {
                CourseRepository.Add(course.CourseName);
                return RedirectToAction("Courses");
            }
            else
            {
                return View("AddCourse",new Course());
            }
        }

        [HttpGet]
        public ActionResult EditCourse(int id)
        {
            var course = CourseRepository.Get(id);
            return View(course);
        }

        [HttpPost]
        public ActionResult EditCourse(Course course)
        {
            if (ModelState.IsValid)
            {
                CourseRepository.Edit(course);
                return RedirectToAction("Courses");
            }
            else
            {
                var course2 = CourseRepository.Get(course.CourseId);
                return View("EditCourse",course2);
            }
        }

        [HttpGet]
        public ActionResult DeleteCourse(int id)
        {
            var course = CourseRepository.Get(id);
            return View(course);
        }

        [HttpPost]
        public ActionResult DeleteCourse(Course course)
        {
            CourseRepository.Delete(course.CourseId);
            return RedirectToAction("Courses");
        }
    }
}

MVC_SIS/MVC_SIS/Controllers/StudentController.cs
using Exercises.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Exercises.Models.Data;
using Exercises.Models.ViewModels;

namespace Exercises.Controllers
{
    public class StudentController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult List()
        {
            var model = StudentRepository.GetAll();

            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var viewModel = new StudentVM();
            viewModel.SetCourseItems(CourseRepository.GetAll());
            viewModel.SetMajorItems(MajorRepository.GetAll());
            viewModel.SetStateItems(StateRepository.GetAll());
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(StudentVM studentVM)
        {
            if (ModelState.IsValid)
            {
                //if (studentVM.Student.GPA<0 || studentVM.Student.GPA>5)
                //{
                //    var viewModel = new StudentVM();
                //    viewModel.SetCourseItems(CourseRepository.GetAll());
                //    viewModel.SetMajorItems(MajorRepository.GetAll());
                //    viewModel.SetStateItems(StateRepository.GetAll());

                //    return View("Add", viewModel);
                //}
                //else
                //{
                    studentVM.Student.Courses = new List<Course>();
                    studentVM.Student.Address = new List<Address>();
                    AddressVM address = new AddressVM();
                    foreach (var courseID in studentVM.SelectedCourseIds)
                        studentVM.Student.Courses.Add(CourseRepository.Get(courseID));

                    studentVM.Student.Major = MajorRepository.Get(studentVM.Student.Major.MajorId);
                    Student modelStudent = studentVM.Student;
                    //Student student = new Student();
                    //student.FirstName = modelStudent.FirstName;
                    //student.LastName = modelStudent.LastName;
                    //student.Courses = modelStudent.Courses;
                    //student.GPA = modelStudent.GPA;
                    //student.Major = modelStudent.Major;
                    int id2 = StudentRepository.Add(modelStudent);
                    address.Student = studentVM.Student;
                    //StudentRepository.SaveAddress(studentVM.Student.StudentId, studentVM.Student.Address);

                    //return RedirectToAction(/*"List"*/"AddAddress", address.Student/*.StudentId*/);
                    return RedirectToAction(/*"List"*/"AddAddress", new { id = id2 }/*.StudentId*/);
                //}
                
            }
            else
            {
                var viewModel = new StudentVM();
                viewModel.SetCourseItems(CourseRepository.GetAll());
                viewModel.SetMajorItems(MajorRepository.GetAll());
                viewModel.SetStateItems(StateRepository.GetAll());

                return View("Add", viewModel);
            }
            
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var student = StudentRepository.Get(id);
            var viewModel = new StudentVM();
            viewModel.SetCourseItems(CourseRepository.GetAll());
            viewModel.SetMajorItems(MajorRepository.GetAll());

            viewModel.Student = student;

            foreach (var course in student.Courses)
                viewModel.SelectedCourseIds.Add(course.CourseId);

            //selectedStudent.FirstName = student.FirstName;
            //selectedStudent.LastName = student.LastName;
            //selectedStudent.Major = student.Major;
            //selectedStudent.GPA = student.GPA;
            //selectedStudent.Courses = student.Courses;

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(StudentVM studentVM)
        {
            if (ModelState.IsValid)
            {
                studentVM.Student.Courses = new List<Course>();

                foreach (var id in studentVM.SelectedCourseIds)
                    studentVM.Student.Courses.Add(CourseRepository.Get(id));

                studentVM.Student.Major = MajorRepository.Get(studentVM.Student.Major.MajorId);

                //StudentRepository.Edit(studentVM.Student);
                int id2 = StudentRepository.Edit(studentVM.Student);
                return RedirectToAction("List", new { id = id2 });
            }
            else
            {
                var student = StudentRepository.Get(studentVM.Student.StudentId);
                var viewModel = new StudentVM();
                viewModel.SetCourseItems(CourseRepository.GetAll());
                viewModel.SetMajorItems(MajorRepository.GetAll());

                viewModel.Student = student;

                foreach (var course in student.Courses)
                    viewModel.SelectedCourseIds.Add(course.CourseId);
                return View("Edit", viewModel);
            }
            
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            StudentRepository.Delete(id);
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult StudentAddress(int id)
        {
            var model = StudentRepository.Get(id);
            var viewModel = new StudentVM();
            //var foundAddressList = model.Address;
            viewModel.Student = model;
            //viewModel.Student.Address = new List<Address>();
            //var emptyStarter = viewModel.Student.Address;
            //emptyStarter.AddRange(model.Address);
            //if (model.Address.Count()==0)
            //{
            //    //return new EmptyResult();
            //}
            //else
            //{
            //if (viewModel.Student.Address.Count()!=0)
            //{

            //if (emptyStarter.Count() != 0)
            //{
                //foreach (var address in model.Address)
                //{

                //    viewModel.Student.Address.Add(address);

                //}
            //}

            //}
            return View(viewModel.Student);
            //}


        }

        [HttpGet]
        public ActionResult AddAddress(int id)
        {
            var currentStudent = StudentRepository.Get(id);
            var viewModel = new AddressVM();
            viewModel.Student = currentStudent;
            //viewModel.SetStateItems(StateRepository.GetAll());
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddAddress(AddressVM addressVM)
        {
            //studentVM.Student.Address = new List<Address>();
            //var student = StudentRepository.Get(addressVM.Student.StudentId);
            //var student = addressVM.Student;
            //var viewModel = new AddressVM();
            //foreach (var address in student.Address)
            //{
            //    viewModel.Address = address;
            //}
            //viewModel.Student=student;
            StudentRepository.SaveAddress(addressVM.Student.StudentId,addressVM.Address);
            //StudentRepository.SaveAddress(studentVM.Student.StudentId, studentVM.Student.Address);

            return RedirectToAction("StudentAddress", new { id= addressVM.Student.StudentId });
        }

        //[HttpGet]
        //public ActionResult DeleteAddress(int id)
        //{
        //    var currentStudent = StudentRepository.Get(id);
        //    var viewModel = new AddressVM();
        //    viewModel.Student = currentStudent;
        //    //viewModel.SetStateItems(StateRepository.GetAll());
        //    return View(viewModel);
        //}

        [HttpPost]
        public ActionResult DeleteAddress(AddressVM addressVM,int studentId, int addressId)
        {
            //StudentRepository.DeleteAddress(addressVM.Student.StudentId, addressVM.Address);
            var student = StudentRepository.Get(studentId);
            Address address = student.Address.Where(a => a.AddressId == addressId).FirstOrDefault();
            student.Address.Remove(address);
            return RedirectToAction("StudentAddress", new { id = studentId });
        }

        [HttpGet]
        public ActionResult EditAddress(int studentId, int addressId)
        {
            var currentStudent = StudentRepository.Get(studentId);
            var viewModel = new AddressVM();
            viewModel.Student = currentStudent;
            viewModel.Address = currentStudent.Address.Where(a => a.AddressId == addressId).FirstOrDefault();
            viewModel.Address.AddressId = addressId;
            //viewModel.SetStateItems(StateRepository.GetAll());
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult EditAddress(AddressVM addressVM, int studentId)
        {
            //studentVM.Student.Address = new List<Address>();
            //var student = StudentRepository.Get(addressVM.Student.StudentId);
            //var student = addressVM.Student;
            //var viewModel = new AddressVM();
            //foreach (var address in student.Address)
            //{
            //    viewModel.Address = address;
            //}
            //viewModel.Student=student;
            //StudentRepository.SaveAddress(addressVM.Student.StudentId, addressVM.Address);
            //StudentRepository.SaveAddress(studentVM.Student.StudentId, studentVM.Student.Address);
            var student = StudentRepository.Get(studentId);
            addressVM.Student = student;
            //var currentAddress = student.Address.Where(a => a.AddressId == addressVM.Address.AddressId).First();
            var currentAddress = addressVM.Address;

MVC_SIS/MVC_SIS/Views/Student/Add.cshtml
@model Exercises.Models.ViewModels.StudentVM

@{
    ViewBag.Title = "Add";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("StudentNav")
    </div>
    <div class="col-xs-12 col-sm-9">
        <div class="row">
            <div class="col-xs-12">
                <h3>Add Student</h3>
                <div class="row">
                    @using (Html.BeginForm())
                    {
                        @*@Html.ValidationSummary()*@
                        <div class="col-xs-12 col-sm-6">
                            <div class="panel panel-primary">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Personal Details</h4>
                                </div>
                                <div class="col-xs-12 col-6">
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label>First Name:</label>
                                            @Html.TextBoxFor(m => m.Student.FirstName, new { @class = "form-control" , placeholder = "First Name" })
                                            <span class="text-danger">@Html.ValidationMessageFor(m=>m.Student.FirstName)</span>
                                        </div>
                                        <div class="form-group">
                                            <label>Last Name:</label>
                                            @Html.TextBoxFor(m => m.Student.LastName, new { @class = "form-control" , placeholder = "Last Name" })
                                            <span class="text-danger">@Html.ValidationMessageFor(m => m.Student.LastName)</span>
                                        </div>
                                        <div class="form-group">
                                            <label>Major:</label>
                                            @Html.DropDownListFor(m => m.Student.Major.MajorId, Model.MajorItems, "-Choose One-", new { @class = "form-control"})
                                            <span class="text-danger">@Html.ValidationMessageFor(m => m.Student.Major.MajorId)</span>
                                        </div>
                                        <div class="form-group">
                                            <label>GPA:</label>
                                            @Html.TextBoxFor(m => m.Student.GPA, new { @class = "form-control"})
                                            <span class="text-danger">@Html.ValidationMessageFor(m => m.Student.GPA)</span>
                                        </div>
                                        <h4>Courses</h4>
                                        <div class="form-group">
                                            @Html.ListBoxFor(m => m.SelectedCourseIds, Model.CourseItems, new { @class = "form-control" })
                                            <span class="text-danger">@Html.ValidationMessageFor(m => m.SelectedCourseIds)</span>
                                        </div>
                                        <button class="btn btn-primary">Save</button>
                                        @*@using (Html.BeginForm("AddAddress", "Student", new { id = Model.Student.StudentId }, FormMethod.Post))
                                        {
                                            <button class="btn btn-primary">Save</button>
                                        }*@
                                    </div>
                                </div>
                            </div>
                        </div>
                        @*<div class="col-xs-12 col-sm-6">
                            <div class="panel panel-warning">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Current Address</h4>
                                </div>
                                <div class="col-xs-12 col-6">
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label>Street Address:</label>
                                            @Html.TextBoxFor(m => m.Student.Address, new { @class = "form-control" })
                                        </div>
                                        <div class="form-group">
                                            <label>Street Address 2(optional):</label>
                                            @Html.TextBoxFor(m => m.Student.Address.Street2, new { @class = "form-control" })
                                        </div>
                                        <div class="form-group">
                                            <label>City:</label>
                                            @Html.TextBoxFor(m => m.Student.Address.City, new { @class = "form-control" })
                                        </div>
                                        <div class="form-group">
                                            <label>State:</label>
                                            @Html.DropDownListFor(m => m.Student.Address.State, Model.StateItems, "-Choose One-", new { @class = "form-control" })
                                        </div>
                                        <h4>Postal Code:</h4>
                                        <div class="form-group">
                                            @Html.TextBoxFor(m => m.Student.Address.PostalCode, new { @class = "form-control" })
                                        </div>
                                        <button class="btn btn-primary">Save</button>
                                    </div>
                                </div>
                            </div>
                        </div>*@
                    }
                </div>
            </div>
        </div>
    </div>
</div>

MVC_SIS/MVC_SIS/Views/Student/AddAddress.cshtml
@model Exercises.Models.ViewModels.AddressVM

@{
    ViewBag.Title = "Add Address";
}

@*<div class="col-xs-12 col-sm-6">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h4 class="panel-title">Current Address</h4>
            </div>
            @foreach (var address in Model.Address)
            {
                <div class="col-xs-12 col-6">
                    <div class="panel-body">
                        <div class="form-group">
                            <label>Street Address:</label>
                            @Html.TextBoxFor(m => m.Student)
                        </div>
                        <div class="form-group">
                            <label>Street Address 2(optional):</label>
                            @Html.TextBoxFor(m => m.Student.Address.Street2, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label>City:</label>
                            @Html.TextBoxFor(m => m.Student.Address.City, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label>State:</label>
                            @Html.DropDownListFor(m => m.Student.Address.State, Model.StateItems, "-Choose One-", new { @class = "form-control" })
                        </div>
                        <h4>Postal Code:</h4>
                        <div class="form-group">
                            @Html.TextBoxFor(m => m.Student.Address.PostalCode, new { @class = "form-control" })
                        </div>
                        <button class="btn btn-primary">Save</button>
                    </div>
                </div>
            }

            
        </div>
    </div>*@
<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("StudentNav")
    </div>
    <div class="col-xs-12 col-sm-9">
        <div class="row">
            <div class="col-xs-12">
                <h3>Add Address</h3>
                <div class="row">
                    @using (Html.BeginForm())
                    {
                        @Html.HiddenFor(m=>m.Student.StudentId)
                        <div class="col-xs-12 col-sm-6">
                                <div class="panel panel-primary">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Current Address</h4>
                                    </div>
                                    <div class="col-xs-12 col-6">
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <label>Street Address:</label>
                                                @Html.TextBoxFor(m => m.Address.Street1, new { @class = "form-control", placeholder = "Street" })
                                            </div>
                                            <div class="form-group">
                                                <label>Street Address 2(optional):</label>
                                                @Html.TextBoxFor(m => m.Address.Street2, new { @class = "form-control" , placeholder = "Street(optional)" })
                                            </div>
                                            <div class="form-group">
                                                <label>City:</label>
                                                @Html.TextBoxFor(m => m.Address.City, new { @class = "form-control", placeholder = "City" })
                                            </div>
                                            <div class="form-group">
                                                <label>State:</label>
                                                @Html.TextBoxFor(m => m.Address.State.StateName, new { @class = "form-control" , placeholder = "State" })
                                            </div>
                                            <h4>Postal Code:</h4>
                                            <div class="form-group">
                                                @Html.TextBoxFor(m => m.Address.PostalCode, new { @class = "form-control" , placeholder = "Postal Code" })
                                            </div>
                                            @*@using (Html.BeginForm("StudentAddress", "Student", new { id = Model.Student.StudentId }, FormMethod.Post))
                                            {
                                                <button class="btn btn-primary">Save</button>
                                            }*@
                                            <button class="btn btn-primary">Save</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

MVC_SIS/MVC_SIS/Views/Student/DeleteAddress.cshtml
@model Exercises.Models.ViewModels.AddressVM
@{
    ViewBag.Title = "Delete Address";
}

<div class="row">
    <div class="col-xs-12">
        <h3>Delete Address</h3>
        @*@Html.ActionLink("Return to List", "StudentAddress", "Admin")*@
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(m => m.Address.AddressId)
            <p>Are you sure that you wish to delete the address: <b>@Html.DisplayFor(m => m.Address.Street1)</b>?</p>
            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
            @Html.ActionLink("Cancel", "Student", null, new { @class = "btn btn-sm btn-info" })
        }
    </div>
</div>

MVC_SIS/MVC_SIS/Views/Student/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("StudentNav")
    </div>
    <div class="col-xs-12 col-sm-9">
        <p>
            This is the student area of the web site.  We can list, add, edit, and delete student information here.
        </p>
        <h3>@Html.ActionLink("List of Students", "List", "Student")</h3>
        <p>This will show a list of the current students enrolled.</p>
        <h3>@Html.ActionLink("Add a Student", "Add", "Student")</h3>
        <p>This will let you add a new student to the list of students enrolled.</p>
        @*<h3>@Html.ActionLink("Edit a Student", "Edit", "Student")</h3>
        <p>This will let you edit a student in the list of students enrolled.</p>
        <h3>@Html.ActionLink("Remove a Student", "Remove", "Student")</h3>
        <p>This will let you delete a student in the list of students enrolled.</p>*@
    </div>
</div>